#!/bin/sh -e
# Script to dispatch NetworkManager events

# Configuration
export VERSION=0.8

export CONFIG_DEBUG=false
export CONFIG_VPN_TABLE=220
export CONFIG_VPN_CONNECTION_ID=AlmgVPNbasic
export CONFIG_VPN_NETWORK=172.16.0.0/12

export ACTION=$NM_DISPATCHER_ACTION
test -z "$ACTION" && export ACTION=$2

if $CONFIG_DEBUG; then
  exec >> /tmp/splitvpn-debug.txt 2>&1

  echo '## ENVIRONMENT'
  env

  echo '## ROUTES BEFORE'
  ip route show table all
fi

# Skip on other connections
test "$CONNECTION_ID" = "$CONFIG_VPN_CONNECTION_ID" || exit 0

# Skip on other actions
case $ACTION in
  (vpn-up)
    ip rule add not from all to $CONFIG_VPN_NETWORK table main priority 128
    ;;
  (vpn-down)
    ip rule del not from all to $CONFIG_VPN_NETWORK table main priority 128
    ;;
  (*)
    exit 0 ;;
esac

if $CONFIG_DEBUG; then
  echo '## ROUTES AFTER'
  ip route show table all
fi

