#!/bin/sh -e
# Script to dispatch NetworkManager events

# Configuration
export VERSION=0.6

export CONFIG_DEBUG=false
export CONFIG_VPN_TABLE=220
export CONFIG_VPN_CONNECTION_ID=VpnAlmg
export CONFIG_VPN_NETWORK=172.16.0.0/12

export ACTION=$NM_DISPATCHER_ACTION
test -z "$ACTION" && export ACTION=$2

if $CONFIG_DEBUG; then
  exec >> /tmp/splitvpn-debug.txt 2>&1

  echo '## ENVIRONMENT'
  env

  echo '## ROUTES BEFORE'
  ip route show table all
fi

# Skip on other connections
test "$CONNECTION_ID" = "$CONFIG_VPN_CONNECTION_ID" || exit 0

# Skip on other actions
case $ACTION in
  (vpn-up)
    # Repopulate the table
    ip route flush table $CONFIG_VPN_TABLE
    ip route add default via $IP4_GATEWAY dev $DEVICE_IFACE proto static table $CONFIG_VPN_TABLE
    ip route add $CONFIG_VPN_NETWORK dev $DEVICE_IFACE proto static src ${IP4_ADDRESS_1%/*} table $CONFIG_VPN_TABLE
    ;;
  (vpn-down)
    # Kill the table
    ip route flush table $CONFIG_VPN_TABLE
    ip route add ${IP4_ROUTE_1%% *} dev $DEVICE_IFACE proto static scope global src ${IP4_ADDRESS_0%/*} table $CONFIG_VPN_TABLE
    ;;
  (*)
    exit 0 ;;
esac

if $CONFIG_DEBUG; then
  echo '## ROUTES AFTER'
  ip route show table all
fi

